#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, make this file executable by "chmod +x post-update".

case " $* " in
    *' refs/heads/publish '*)

    echo "Pushing changes into CVS for project '__PROJECT__'"
    /home/davp/gitcvs/bin/gitcvs-export __PROJECT__
    
    ;;

esac
exec git-update-server-info
